name: "Terraform AWS CI/CD"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'aws/**', '.github/workflows/**' ]

jobs:
  terraform:
    name: "Validacao Estrita e Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v3

      - name: Configurar Credenciais AWS via Secrets
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # ==========================================
      # FASE 1: BOOTSTRAP (Idempotente)
      # ==========================================
      - name: Verificar e Criar S3 State
        run: |
          BUCKET_NAME="techstock-tfstate-joao-7733"
          if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket $BUCKET_NAME pronto."
          else
            echo "Criando fundacao de estado: $BUCKET_NAME"
            aws s3 mb s3://$BUCKET_NAME --region us-east-1
          fi

      # ==========================================
      # FASE 2: INICIALIZAÇÃO
      # ==========================================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Infraestrutura - Init
        run: terraform init
        working-directory: ./aws

      # ==========================================
      # FASE 3: VALIDAÇÃO TOTAL (BLOQUEANTE)
      # ==========================================
      - name: Infraestrutura - Validate (Sintaxe e Estrutura)
        run: terraform validate
        working-directory: ./aws

      - name: Infraestrutura - Plan (Simulacao Real na AWS)
        run: terraform plan -out=tfplan
        working-directory: ./aws

      # ==========================================
      # FASE 4: EXECUÇÃO (APENAS SE A FASE 3 PASSAR)
      # ==========================================
      - name: Infraestrutura - Apply (Deploy do Plano Validado)
        run: terraform apply -auto-approve tfplan
        working-directory: ./aws

      - name: 🚀 Sincronizar Frontend para o S3
        run: |
          aws s3 sync . s3://techstock-frontend-ui-joao --delete --exclude "*.tf" --exclude "*.sh" --exclude ".git*"

