name: "Terraform AWS CI/CD"

on:
  push:
    branches: [ main ]
    paths: [ 'aws/**', 'bootstrap/**' ]

jobs:
  terraform:
    name: "Deploy Multi-Fase: Bootstrap e Infraestrutura"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v3

      - name: Configurar Credenciais AWS via Secrets
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # ==========================================
      # FASE 1: BOOTSTRAP (Cria o S3 do Estado)
      # ==========================================
      - name: Bootstrap - Init
        run: terraform init
        working-directory: ./bootstrap

      - name: Bootstrap - Apply
        run: terraform apply -auto-approve
        working-directory: ./bootstrap

      # ==========================================
      # FASE 2: INFRAESTRUTURA (Usa o S3 recém-criado)
      # ==========================================
      - name: Infraestrutura - Init
        run: terraform init
        working-directory: ./aws

      - name: Infraestrutura - Validate
        run: terraform validate
        working-directory: ./aws

      - name: Infraestrutura - Apply
        run: terraform apply -auto-approve
        working-directory: ./aws
